version: '3'
services:
  flaskapitest:
    build: ./
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=yogesh
      - MYSQL_DATABASE=Mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      
volumes:
  mysql_data: